rm build*.*
<<<<<<< Updated upstream
make clean all OVERRIDEVERSIONCHECK=1 %* -j || exit /b %ERRORLEVEL%
make clean all FPC=c:\pp\bin\i386-win32\ppcrossx64 OVERRIDEVERSIONCHECK=1 CPU_TARGET=x86_64 OS_TARGET=win64 CPU_SOURCE=x86_64 OS_SOURCE=win64 -j || exit /b %ERRORLEVEL%
make clean all OVERRIDEVERSIONCHECK=1 "CROSSOPT=-O4 -Cparmv5te" OS_TARGET=linux CPU_TARGET=arm || exit /b %ERRORLEVEL%
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=powerpc64 || exit /b %ERRORLEVEL%
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=sparc || exit /b %ERRORLEVEL%
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=powerpc || exit /b %ERRORLEVEL%
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=mipsel || exit /b %ERRORLEVEL%
=======
make clean all OVERRIDEVERSIONCHECK=1 %* -j
IF NOT ERRORLEVEL EXIT /B 1
make clean all FPC=c:\pp\bin\i386-win32\ppcrossx64 OVERRIDEVERSIONCHECK=1 CPU_TARGET=x86_64 OS_TARGET=win64 CPU_SOURCE=x86_64 OS_SOURCE=win64 -j
IF NOT ERRORLEVEL 0 EXIT /B 1
make clean all OVERRIDEVERSIONCHECK=1 "CROSSOPT=-O4 -Cparmv5te" OS_TARGET=linux CPU_TARGET=arm
IF NOT ERRORLEVEL 0 EXIT /B 1
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=powerpc64
IF NOT ERRORLEVEL 0  EXIT /B 1
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=sparc
IF NOT ERRORLEVEL 0 EXIT /B 1
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=powerpc
IF NOT ERRORLEVEL 0 EXIT /B 1
make clean all OVERRIDEVERSIONCHECK=1 OS_TARGET=linux CPU_TARGET=mipsel
IF NOT ERRORLEVEL 0 EXIT /B 1
>>>>>>> Stashed changes
